name: CI-Cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo código
      uses: actions/checkout@v4.1.7
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
    - name: Build Image
      run: docker build -t adenilsonkon/api-cicd:latest . --file Dockerfile 
    - name: Push Image
      run: docker push adenilsonkon/api-cicd:latest
        
          
      
