name: CI-Cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo código
      uses: actions/checkout@v4.1.7
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: docker build -t adenilsonkon/api-cicd:v${{ github.run_number }} . --file Dockerfile 
    - name: Push Image
      run: |
        docker push adenilsonkon/api-cicd:v${{ github.run_number }}
        docker tag adenilsonkon/api-cicd:v${{ github.run_number }} adenilsonkon/api-cicd:latest
        docker push adenilsonkon/api-cicd:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Obtendo código
      uses: actions/checkout@v4.1.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: configurando cluster
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
    - name: Deploy no cluster EKS
      uses: Azure/k8s-deploy@v5
      with:
          manifests: |
            deployment.yaml
          images: adenilsonkon/api-cicd:v${{ github.run_number }}
          arguments: --validate=false 

        


          
          
      
